<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All Alerts</name>
   <tag></tag>
   <elementGuidId>46788115-d96c-47bc-8497-7b1b9ce291e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;menu-item.group_work.path:menu-item.all_alerts.path&quot;)[count(. | //a[@id = 'menu-item.group_work.path:menu-item.all_alerts.path' and (text() = 'All Alerts' or . = 'All Alerts')]) = count(//a[@id = 'menu-item.group_work.path:menu-item.all_alerts.path' and (text() = 'All Alerts' or . = 'All Alerts')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuCursorWait</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-item.group_work.path:menu-item.all_alerts.path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/netreveal/screen/view.do?secure=5otmYtjtLuOMQUuhhegBbEWi8cq9tF18yvMwRj2DvcYQfluhKk-cW9Tqiimr1uHJ65ke4R1Fz4llFOAZGAT0Lgkk9Y6G_qr-vFFNFkSeUFzs90Oy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Alerts</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item.group_work.path:menu-item.all_alerts.path&quot;)</value>
   </webElementProperties>
</WebElementEntity>
